arch_en: blconv_b
arch_de: ar_transformer_xs
num_channel: 13
len_seq: 0
use_bpe: false
use_gated_attention: true
gating_type: elementwise
categories:
- ''
- A
- B
- C
- D
- E
- F
- G
- H
- I
- J
- K
- L
- M
- N
- O
- P
- Q
- R
- S
- T
- U
- V
- W
- X
- Y
- Z
- Ä
- Ö
- Ü
- a
- b
- c
- d
- e
- f
- g
- h
- i
- j
- k
- l
- m
- n
- o
- p
- q
- r
- s
- t
- u
- v
- w
- x
- y
- z
- ä
- ö
- ü
- ß
checkpoint: /home/woody/iwso/iwso214h/imu-hwr/results/hwr2/Baseline-AR-XS-blconv_b/ar_transformer_xs__onhw_wd_word_rh/fold_0/0/checkpoints/best_cer.pth
dir_dataset: /home/woody/iwso/iwso214h/imu-hwr/data/onhw_wd_word_rh
idx_fold: 0
cache: true
device: cuda
seed: 42
num_worker: 4
size_batch: 64
max_len: 200
decoder: ar
method: greedy
beam_size: 4
alpha: 0.6
eos_bias: 0.0
min_len: 0
min_len_ratio: 0.0
lm_path: null
lm_weight: 0.0
insertion_bonus: 0.0
length_bonus: 0.0
nbest_size: 16
outdir: /home/woody/iwso/iwso214h/imu-hwr/results/hwr2/decode_study
